### PR TITLE
fixing pr items and implementation errors

### PR DESCRIPTION
**Pull request by psbanka**
- Fixing `package.json` version
- Adding dependency to `gm`, which the `webdrivercss` folks forgot (https://github.com/webdriverio/webdrivercss/issues/70)
- Fixing path errors which were discovered when re-installing in a real CI environment
- Addressing PR issues from last request.

### CODE REVIEW

**Comment by psbanka** [comment]
Also addresses https://github.com/cyaninc/webdriverio-server/issues/8

**Comment by psbanka** [comment]
Self-merging to finish deployment.

**Comment by job13er** [comment]
:+1:

**Comment by job13er** [comment]
I'm not sure I see how this addresses #8 though. Was there a change to the exec.sh that didn't make it into the pr?

**Pull request merged**
